import json

from .affine_nodes import AFFINE_NODE_CLASS_MAPPINGS, AFFINE_NODE_DISPLAY_NAME_MAPPINGS
from .option_nodes import OPTION_NODE_CLASS_MAPPINGS, OPTION_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **AFFINE_NODE_CLASS_MAPPINGS,
    **OPTION_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **AFFINE_NODE_DISPLAY_NAME_MAPPINGS,
    **OPTION_NODE_DISPLAY_NAME_MAPPINGS,
}

print("WAS Affine has loaded {} nodes.".format(len(NODE_CLASS_MAPPINGS)))
print("Node Classes Loaded:")
print(json.dumps(list(NODE_CLASS_MAPPINGS.keys()), indent=2))

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
